[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "conan-explorer"
authors = [{name = "Péter Gosztolya and Contributors"}]
version = "2.2.0a1"
requires-python = ">=3.8"
description = "GUI for Conan users providing an easy way to install and manage local packages and launch application from them."
repository = "https://github.com/goszpeti/conan_explorer"
readme = "README.md"
keywords = ["conan", "gui"]
license = "LGPL-3.0-only"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Environment :: X11 Applications :: Qt",
    "Environment :: Win32 (MS Windows)"
]
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
]

[project.optional-dependencies]
dev = ["ReportLab>=1.2", "RXP"]
test = ["docutils>=0.3", "pack ==1.1, ==1.3"]

[project.gui_scripts]
conan_explorer = "conan_explorer.__main__:run_conan_explorer"
conan_explorer= "conan_explorer.__main__:run_conan_explorer",

[tool.setuptools]
packages = [ { include = "conan_explorer", from = "src" },]

[tool.setuptools.package-data]
"conan_explorer" = ["**/*.pyi"]

[tool.ruff]
line-length=88
target-version = "py38"

[tool.autopep8]
max_line_length = 88
