# Form implementation generated from reading ui file 'c:\repos\conan_app_launcher\src\conan_app_launcher\ui\dialogs\file_editor_selection\file_editor_selector.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 239)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description_label = QtWidgets.QLabel(Form)
        self.description_label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.edit_frame = QtWidgets.QFrame(Form)
        self.edit_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.edit_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.edit_frame.setObjectName("edit_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.edit_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.file_edit = QtWidgets.QLineEdit(self.edit_frame)
        self.file_edit.setObjectName("file_edit")
        self.gridLayout.addWidget(self.file_edit, 0, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.edit_frame)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.edit_frame)
        self.button_box = QtWidgets.QDialogButtonBox(Form)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.description_label.setText(_translate("Form", "<html><head/><body><p>Select editor executable to use with right click &quot;Edit File&quot; option. </p><p>Most editors will work, though they have to support on the commandline the following calling convention: \'&lt;editor_executable&gt; &lt;file_name&gt;\'.</p></body></html>"))
        self.browse_button.setText(_translate("Form", "Browse"))
