# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/peter/Repos/app_grid_conan/src/conan_app_launcher/ui/qt/app_grid.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.console_scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.console_scroll_area.setGeometry(QtCore.QRect(10, 470, 771, 121))
        self.console_scroll_area.setWidgetResizable(True)
        self.console_scroll_area.setObjectName("console_scroll_area")
        self.console_scroll_area_widgets = QtWidgets.QWidget()
        self.console_scroll_area_widgets.setGeometry(QtCore.QRect(0, 0, 769, 119))
        self.console_scroll_area_widgets.setObjectName("console_scroll_area_widgets")
        self.console = QtWidgets.QTextBrowser(self.console_scroll_area_widgets)
        self.console.setGeometry(QtCore.QRect(0, 0, 771, 121))
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.console_scroll_area.setWidget(self.console_scroll_area_widgets)
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 0, 781, 471))
        self.tabs.setObjectName("tabs")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tab_scroll_area = QtWidgets.QScrollArea(self.tab_1)
        self.tab_scroll_area.setGeometry(QtCore.QRect(0, 0, 771, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_scroll_area.sizePolicy().hasHeightForWidth())
        self.tab_scroll_area.setSizePolicy(sizePolicy)
        self.tab_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tab_scroll_area.setWidgetResizable(True)
        self.tab_scroll_area.setAlignment(QtCore.Qt.AlignCenter)
        self.tab_scroll_area.setObjectName("tab_scroll_area")
        self.tab_scroll_area_widgets = QtWidgets.QWidget()
        self.tab_scroll_area_widgets.setGeometry(QtCore.QRect(0, 0, 755, 439))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_scroll_area_widgets.sizePolicy().hasHeightForWidth())
        self.tab_scroll_area_widgets.setSizePolicy(sizePolicy)
        self.tab_scroll_area_widgets.setMinimumSize(QtCore.QSize(752, 359))
        self.tab_scroll_area_widgets.setBaseSize(QtCore.QSize(752, 359))
        self.tab_scroll_area_widgets.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_scroll_area_widgets.setObjectName("tab_scroll_area_widgets")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_scroll_area_widgets)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 445))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.tab1_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.tab1_grid_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.tab1_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.tab1_grid_layout.setObjectName("tab1_grid_layout")
        self.app_layout = QtWidgets.QVBoxLayout()
        self.app_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.app_layout.setObjectName("app_layout")
        self.tab1_grid_layout.addLayout(self.app_layout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab1_grid_layout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tab1_grid_layout.addLayout(self.verticalLayout_6, 0, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tab1_grid_layout.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tab1_grid_layout.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab1_grid_layout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.tab1_grid_layout.setColumnStretch(0, 1)
        self.tab1_grid_layout.setColumnStretch(1, 1)
        self.tab1_grid_layout.setColumnStretch(2, 1)
        self.tab1_grid_layout.setColumnStretch(3, 1)
        self.tab1_grid_layout.setRowStretch(0, 1)
        self.tab1_grid_layout.setRowStretch(1, 1)
        self.tab1_grid_layout.setRowStretch(2, 1)
        self.tab_scroll_area.setWidget(self.tab_scroll_area_widgets)
        self.tabs.addTab(self.tab_1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 798, 20))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_help = QtWidgets.QMenu(self.menu_bar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menu_bar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_about_action = QtWidgets.QAction(MainWindow)
        self.menu_about_action.setObjectName("menu_about_action")
        self.menu_help.addAction(self.menu_about_action)
        self.menu_bar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.875pt;\"><br /></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_1), _translate("MainWindow", "Basics"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menu_about_action.setText(_translate("MainWindow", "About"))
