# Form implementation generated from reading ui file 'c:\repos\conan_app_launcher\src\conan_app_launcher\ui\dialogs\reorder_dialog\reorder_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_rearrange_dialog(object):
    def setupUi(self, rearrange_dialog):
        rearrange_dialog.setObjectName("rearrange_dialog")
        rearrange_dialog.resize(443, 331)
        self.gridLayout = QtWidgets.QGridLayout(rearrange_dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.list_view = QtWidgets.QListView(rearrange_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.list_view.sizePolicy().hasHeightForWidth())
        self.list_view.setSizePolicy(sizePolicy)
        self.list_view.setObjectName("list_view")
        self.gridLayout.addWidget(self.list_view, 0, 0, 1, 1)
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("vertical_layout")
        self.move_up_button = QtWidgets.QPushButton(rearrange_dialog)
        self.move_up_button.setObjectName("move_up_button")
        self.vertical_layout.addWidget(self.move_up_button)
        self.line = QtWidgets.QFrame(rearrange_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.vertical_layout.addWidget(self.line)
        self.move_down_button = QtWidgets.QPushButton(rearrange_dialog)
        self.move_down_button.setObjectName("move_down_button")
        self.vertical_layout.addWidget(self.move_down_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vertical_layout.addItem(spacerItem)
        self.gridLayout.addLayout(self.vertical_layout, 0, 1, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(rearrange_dialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(False)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 1, 0, 1, 1)

        self.retranslateUi(rearrange_dialog)
        self.button_box.accepted.connect(rearrange_dialog.accept) # type: ignore
        self.button_box.rejected.connect(rearrange_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(rearrange_dialog)

    def retranslateUi(self, rearrange_dialog):
        _translate = QtCore.QCoreApplication.translate
        rearrange_dialog.setWindowTitle(_translate("rearrange_dialog", "Rearrange App Grid"))
        self.move_up_button.setText(_translate("rearrange_dialog", "Move up"))
        self.move_down_button.setText(_translate("rearrange_dialog", "Move down"))
