# Form implementation generated from reading ui file 'c:\repos\conan_app_launcher\src\conan_app_launcher\ui\views\plugins_manager\plugins.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 454)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, -1, 2, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_plugin_button = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\repos\\conan_app_launcher\\src\\conan_app_launcher\\ui\\views\\plugins_manager\\../../assets/icons/plus_rounded.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.add_plugin_button.setIcon(icon)
        self.add_plugin_button.setObjectName("add_plugin_button")
        self.verticalLayout.addWidget(self.add_plugin_button)
        self.toggle_plugin_button = QtWidgets.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\repos\\conan_app_launcher\\src\\conan_app_launcher\\ui\\views\\plugins_manager\\../../assets/icons/hide.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.toggle_plugin_button.setIcon(icon1)
        self.toggle_plugin_button.setObjectName("toggle_plugin_button")
        self.verticalLayout.addWidget(self.toggle_plugin_button)
        self.remove_plugin_button = QtWidgets.QPushButton(self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\repos\\conan_app_launcher\\src\\conan_app_launcher\\ui\\views\\plugins_manager\\../../assets/icons/minus_rounded.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.remove_plugin_button.setIcon(icon2)
        self.remove_plugin_button.setObjectName("remove_plugin_button")
        self.verticalLayout.addWidget(self.remove_plugin_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 1, 2, 1)
        self.plugins_tree_view = QtWidgets.QTreeView(Form)
        self.plugins_tree_view.setObjectName("plugins_tree_view")
        self.gridLayout.addWidget(self.plugins_tree_view, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_plugin_button.setText(_translate("Form", "Add new Plugin"))
        self.toggle_plugin_button.setText(_translate("Form", "Enable / Disable"))
        self.remove_plugin_button.setText(_translate("Form", "Remove Plugin"))
